### ISSUE TITLE
Color via filter is not changing if someone saved the options panel settings

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#101]
**To Reproduce**
1. Activate the WP Review plugin, and then activate the theme which has the color filter
2. Now go to the WP Review Settings page and click the save button
3. Now if you activate any other WordPress theme which doesn't have the filter then colors remain the same (which is fine)
4. B if you try to activate the theme which has the color filter with the different colors, then new colors are not getting applied in the settings.

**Expected behavior**
Colors should change if the newly activated theme has different colors set using the filter. If not it should just keep the old theme's colors.

**Comment by truong-mts** [comment]
As I said before, custom colors can be lost if users activate new theme which has that filter

**Comment by surajv** [comment]
It should not affect the custom colors set in the single posts, it should affect only global values. and if single posts are not using the custom colors it will automatically pick the global colors.

And the above issue is the different one, please try to reproduce it.

**Comment by truong-mts** [comment]
Yes. I mean global color options in the WP Review settings page.

I agree with steps 1, 2, 3 and it works without any problem.

The hook `wp-review_default_colors` is for default colors of global colors (you may be confused). When you install the plugin and do not hit the `Save` button in the settings page anytime, WP Review options will not be set, the plugin uses default options which we set in code (and we change default colors in our theme via that hook). Once you hit the `Save` button, WP Review option will be set, the plugin will take options from the database, so default colors will not affect anymore.

Does it make sense?

**Comment by surajv** [comment]
Yeah but what if another theme wants to change the colors as per that theme's color scheme? It will just make that filter useless for the themes if we once save the options.

Anyways I think we can live with it as of now. Closing it.
