### ISSUE TITLE
Missing files in the single page editor

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#109]
These are the files which are showing as missing on the single page editor

```
…/wp-content/plugins/wp-review/public/sourcemaps/wp-review.css.map
…/wp-content/plugins/wp-review/public/js/js.cookie.min.js.map
```

**Comment by truong-mts** [comment]
Does it show in the browser console only?

**Comment by surajv** [comment]
Yeah I think so, user reported it here https://wordpress.org/support/topic/missong-files-on-pageload/
