### ISSUE TITLE
Magnific popup JS & CSS loading in the frontend

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#118]
Please remove them from the frontend as we don't need them.

v5.1.8 branch is https://github.com/MyThemeShopTeam/WP-Review/tree/remote_purchase

**Comment by surajv** [comment]
Also looks like other review related files are loading everywhere in the frontend, we should enqueue them only if the post contains the review or review on thumbnail is showing using the custom code.

**Comment by truong-mts** [comment]
Reviews can be added in widgets so we can't check to load CSS files correctly. We can do this with JS files only.
