### ISSUE TITLE
If there are no 'Review Items' then review schema data is not printing in the frontend

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#123]
If there are no review items http://i.mythemeshop.com/QeBurb

Then this data is not printing in the frontend: http://i.mythemeshop.com/KuhEHG

Please also check the same in the pro version.

**Comment by truong-mts** [comment]
I think it should not print if there is no rating, no?

**Comment by surajv** [comment]
Yeah but visitor rating and visitors schema is enabled.
