### ISSUE TITLE
How to get query with custom categories?

### ISSUE THREAD

**Issue by DeoThemes** [MyThemeShopTeam/WP-Review#129]
I'm trying to get custom query in a plugin using this function, but stuck on the categories. Option **cat** should accept id's of categories, but when I pass them I still get query with all the categories. I'm not using filter because the values are dynamic and come from plugin settings. For now I just hard-code them.

Here is the code example:

```
$review_args = [
	'post_type'             => 'post',
	'post_status'           => 'publish',
	'ignore_sticky_posts'   => -1,
	'review_type'           => 'star',
	'cat'                   => '2, 5',
	'page'                  => '',
	'post_num'              => '3',
	'clear_cache'           => true,
];

$query = wp_review_get_reviews_query( 'toprated', $review_args );
```

**Comment by DeoThemes** [comment]
Found my mistake, **cat** accepts integer, single id of the category. Issue is resolved :)

**Comment by surajv** [comment]
Hello @DeoThemes,
Glad to know that.
If anything else, please let us know.
Thank you.
