### ISSUE TITLE
Review nag notice shows up too early

### ISSUE THREAD

**Issue by balazsmts** [MyThemeShopTeam/WP-Review#133]
**Describe the bug**
I can see the notice right after activating it for the first time:

> Hey, we noticed you have created over 10 reviews from WP Review - that’s awesome! Could you please do us a BIG favor and give it a 5-star rating on WordPress to help us spread the word and boost our motivation?

https://take.ms/UMFP1

**To Reproduce**
Activate the latest version of the plugin on a clean test site.

**Expected behavior**
The notice should show up only after 10 reviews were written.

**Screenshots**
https://take.ms/UMFP1

**Comment by truong-mts** [comment]
@surajv Why do you comment out the check code? https://github.com/MyThemeShopTeam/WP-Review/commit/54151c86073a094ae0bb1061a49970db1eb54613#diff-6baefe7d1d48a0c8af249979ec182d8eR41

Is this a mistake?

**Comment by truong-mts** [comment]
@surajv You also changed this https://github.com/MyThemeShopTeam/WP-Review/commit/54151c86073a094ae0bb1061a49970db1eb54613#diff-6baefe7d1d48a0c8af249979ec182d8eR126

**Comment by surajv** [comment]
Ah, maybe I disabled those checks to style that notice then forgot.

**Comment by truong-mts** [comment]
Ok. Let me fix it
