### ISSUE TITLE
Why do we have Pro version related code in the free version?

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#134]
https://github.com/MyThemeShopTeam/WP-Review/blob/master/admin/admin.php check this file, I am not sure about other files, so please check them as well.

**Comment by truong-mts** [comment]
@surajv Please give me which line of code

**Comment by surajv** [comment]
https://github.com/MyThemeShopTeam/WP-Review/blob/master/admin/admin.php#L121
https://github.com/MyThemeShopTeam/WP-Review/blob/master/admin/admin.php#L192-L347

**Comment by truong-mts** [comment]
@surajv Those functions are used to print the admin options which are disabled, not completely removed

**Comment by surajv** [comment]
I see okay
