### ISSUE TITLE
I want to ask a question, regarding Rank Math plugin

### ISSUE THREAD

**Issue by newkhan** [MyThemeShopTeam/WP-Review#145]
I have been using rank math on my website [AJ Quotes](http://ajquotes.com) since I have started the AJ Quotes the rank math plugin really helped me , I enjoyed working with rank math but from last 2 weeks I found a problem with rank math updates, since I have updated the plugin, few of its options are missing like API indexing settings. Kindly provide the best solution for my problem, so I can start my work again with rank math.

**Comment by balazsmts** [comment]
Hello, for questions related to Rank Math please use the official support forums: http://support.rankmath.com
