### ISSUE TITLE
If rating is not allowed for the Guests, show message

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#157]
Please inform here: https://wordpress.org/support/topic/message-prompt-for-rating/#post-12770583

If guest users can't submit a rating, then please show this message on hover.

`Rating is disabled for the guests, please log in to submit.`

Let's add the same thing in the Pro version.

**Comment by truong-mts** [comment]
@surajv How should we show that message? There is no hover on mobile. So I'm thinking to place that message to the bottom of the User Reviews row.

**Comment by surajv** [comment]
I think showing it all the time will not look good, then let's show it only when someone tries to rate it by clicking.

**Comment by truong-mts** [comment]
Ok. When clicking to the star rating, how should we show the message? Via popup, tooltip or just a message in the bottom? I like just show a message in the bottom because we won't need to enqueue a js library

**Comment by surajv** [comment]
Sure let's show at the bottom.
