### ISSUE TITLE
Add Pros and Cons Post Type or Section to Review Plugin

### ISSUE THREAD

**Issue by ghost** [MyThemeShopTeam/WP-Review#16]
Add Pros and Cons Post Type or Section to Review Plugin, it would be great to have an option to review the pros and the cons specifically of products not just a summary. Some people would love to rate the pros and cons of items. Please make this easier to do in order to have a section that we can add to before or after the review itself.

**Comment by truong-mts** [comment]
Hi @ghost,

Thank you for your suggestion. We will consider to add this feature in the future.

**Comment by surajv** [comment]
This feature is present in the pro version, so closing it.
