### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by gooloonetwork** [MyThemeShopTeam/WP-Review#166]
Hello,
i'm a german user of WP Review Pro and didn't find any solutions to translate Frontend Data, f.ex. "Leave a Reply" and "User Rating". Please give an Option to translate to german.

**Comment by truong-mts** [comment]
@gooloonetwork Thanks for reporting the issue. We are working on an update and will release it soon.

**Comment by gooloonetwork** [comment]
This doesn't work; it still shows in English everywhere. Also, i shouldn't have to download another Plugin for a simple Translation-Tool, as i already paid for the Pro Version.

**Comment by gooloonetwork** [comment]
> @gooloonetwork Thanks for reporting the issue. We are working on an update and will release it soon.
> 
> You can fix this in your site using Loco Translate plugin. After installing Loco Translate, please go to Loco Translate > Plugins > WP Review > Edit Template, hit Sync button then Save. After that, you can translate remaining strings normally.

This doesn't work; it still shows in English everywhere. Also, i shouldn't have to download another Plugin for a simple Translation-Tool, as i already paid for the Pro Version.

**Comment by gooloonetwork** [comment]
[wp-review.txt](https://github.com/MyThemeShopTeam/WP-Review/files/6246887/wp-review.txt)

**Comment by truong-mts** [comment]
Please update the plugin the latest version and use a translation plugin to translate to German. The plugin does not contain all translations so if your language is not supported, you need to translate by yourself.

**Comment by gooloonetwork** [comment]
Well, i can translate it, but it doesn't show. Neither the Values in the Backend, nor what Commenters/Reviewers see, is being translated. It still showed everything in english. After trying for multiple days and of course clearing my cache multiple times, i uninstalled Loco Translate.
