### ISSUE TITLE
Default settings for all posts (rating type, items, etc.)

### ISSUE THREAD

**Issue by chriszj** [MyThemeShopTeam/WP-Review#20]
Hi, first of all great plugin! its simple and clean.

It would be nice if it supports default settings to display the review box on all post without editing one by one. This is like, set $default_type = 'star', $default_items = '', and so on. Then when I call the function wp_review_get_data() in my theme it display the review box in all post without having to previously edit them (posts without 'type' post_meta falls back in the default settings, and so on).

 I managed to have a workaround by modifying a little wp_review_get_data() and the wp_review_enqueue(), but this workaround is not ideal in the future, The ideal solution would be to add these default fields in the admin pannel and then the functions pick the settings from there.

**Comment by truong-mts** [comment]
Hi @chriszj,

Did you set default settings in WP-Admin > Settings > WP Review > Global > Defaults?
