### ISSUE TITLE
Hide featured image placeholder in widget

### ISSUE THREAD

**Issue by DeoThemes** [MyThemeShopTeam/WP-Review#52]
Hello.
Is there a way to filter how featured images shown in the widget? Currently it shows placeholder, but I can't find a filter or option how to remove placeholder if no featured image set. Maybe some class would be nice, so I can remove it via JS. Currently I can see the only way is to filter some classes and hide an image based on this condition.

Overall , great plugin.

**Comment by truong-mts** [comment]
Hi @DeoThemes,

Thank you for your suggestion. We will add `wp-review-no-thumbnail` class to posts which have no thumbnail on widgets. This will be implemented after version 5.0.0 is released.
