### ISSUE TITLE
Description field no longer work

### ISSUE THREAD

**Issue by DeoThemes** [MyThemeShopTeam/WP-Review#60]
When I save description textarea, after refresh it's empty and not showing in front-end.

**Comment by truong-mts** [comment]
Hi @DeoThemes,

Which version are you using?

**Comment by DeoThemes** [comment]
I was using version 4, but today upgraded to latest 5.0.1 and description disappeared. I'm using Gutenberg by the way.

**Comment by truong-mts** [comment]
Description content field appears with me but it does save when using with Gutenberg. Can you capture a screenshot and give me. And do you see any errors from browser console?

**Comment by ankit-d** [comment]
Hello @truong-mts, 

It's not working for me as well,
1) When we add in a new post then https://www.useloom.com/share/38df5532ebde46a7ba0a00050ccae516

2) When we update the description content https://www.useloom.com/share/334695c6f1454e02b25bae894d61222b
