### ISSUE TITLE
select2 JS-Issue: Empty customizer when WP Review Pro is activated

### ISSUE THREAD

**Issue by HeyHeyDaniel** [MyThemeShopTeam/WP-Review#62]
I'm using WP Review Pro together with the theme OceanWP. The problem is, when the plugin is activated, the customizer is nearly empty and looks like this: https://image.ibb.co/cqzZAU/customizer.png

The developers said, that the issue is coming from select2 JS. When you guys could update to the latest version of select2 JS, the issue should be solved.

Thank you very much!

**Comment by HeyHeyDaniel** [comment]
Hi surajv,
yes, I use the latest version, I think.
Is "select2 JS" updated in the latest version?
KR, Martin

**Comment by truong-mts** [comment]
We did this in WP Review plugin. We will add this to the pro version and release it.

Thanks.

**Comment by surajv** [comment]
Hi, we have found the issue and will be fixed in the next update.

The new version will be released after a few hours.

Hope this helps, thank you.
