### ISSUE TITLE
Latest Reviews Widget not Updating

### ISSUE THREAD

**Issue by ankit-d** [MyThemeShopTeam/WP-Review#67]
With reference to this https://wordpress.org/support/topic/latest-reviews-widget-not-updating/#post-10685235 I have created a fresh post with point rating http://take.ms/ESNB0 . I am not getting this in Recent Tab http://take.ms/XIls7

**Comment by truong-mts** [comment]
@ankit-d Can you give me the screenshot about your widget config?

**Comment by ankit-d** [comment]
Hello @truong-mts http://take.ms/ueq4R you can enable only Recent Tab also

**Comment by surajv** [comment]
Fixed in 8edce10ff117276a86c8ef91e0a4eae4010d77b2
