### ISSUE TITLE
Shortcode and Function for showing average of users' rating

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#7]
Something like [wp-review-user-total] and function.

**Comment by surajv** [comment]
Please mention this new shortcode in the filter list file.

**Comment by truong-mts** [comment]
It is mentioned here https://github.com/MyThemeShopTeam/WP-Review/blob/v5.0.0/filter-list.php#L729

**Comment by surajv** [comment]
Also please remove the pro version related filters from that file.

**Comment by truong-mts** [comment]
I removed
