### ISSUE TITLE
Gutenberg conflict - 500 Error

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#71]
User reported this

> Version 5 of the plugin has stopped Gutenberg from saving drafts on a number of my sites – deactivating WP Review resolved it. It's causing a 500 error (viewable in JavaScript console).
> 
> I've tried logging this ticket on your main support site but it's currently showing as being unavailable due to maintenance.

**Comment by surajv** [comment]
Errors in the search console:

```
GET https://artiss.blog/wp-admin/post.php?meta_box=1&action=edit&classic-editor&post=98091 500 . index.js?ver=1535722933:1

Uncaught (in promise) Response {type: "basic", url: "https://artiss.blog/wp-admin/post.php?meta_box=1&action=edit&classic-editor&post=98091", redirected: true, status: 500, ok: false, …} . VM384 post.php:1
```

**Comment by truong-mts** [comment]
Can you ask him the error log? I can replicate this issue on my local. The above message does not help me find it
