### ISSUE TITLE
Default global settings not getting applied in the single post

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#81]
The user reported this:

> Hi. I've set the user ratings to Visitor Rating Only in the settings for WP Review but when I create a new post I still have to change this manually: https://www.dropbox.com/s/qmi9f98ysmgdt0h/Screenshot%202018-09-23%2014.49.39.png?dl=0
> Also, as you can see in the screenshot above, I have set the default review type to points but the user ratings are still stars and I have to change that manually every time.
> Why is this not working?
>

**Comment by truong-mts** [comment]
Should `User Rating Type` option be affected by global `Review Type` option?
