### ISSUE TITLE
Schema not printing issues if user reviews are disabled in the 4.x reviews

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#83]
If in the v4.x, this option is selected http://take.ms/aX0Qk
Then https://monosnap.com/direct/WX5hI4IVYSoshCjPNbv3vfWUoRQSdb this option should be selected.

Currently, it is set to the visitor rating schema for all the old posts, which is not printing any schema data if visitor rating is disabled.

**Comment by surajv** [comment]
Author rating is always selected, even after changing and saving the post http://take.ms/eAc7P

**Comment by truong-mts** [comment]
Did you enable visitors rating?

**Comment by surajv** [comment]
Ah yes, that was not disabled.
