### ISSUE TITLE
Remove unnecessary scripts from the non WP Review admin pages

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#93]
https://github.com/MyThemeShopTeam/WP-Review/blob/96cfb04e6e1ee325008ad0f255d9b77d909fa907/includes/enqueue.php#L23-L40

Let's remove cookie script, admin-ajax.php and any other file which are loading on non-WP Review related pages.

These scripts should load only on the pages where they are required.

**Comment by truong-mts** [comment]
The code you gave is from the frontend. I fixed in the backend in other files.
