### ISSUE TITLE
Compatibility issue with RM

### ISSUE THREAD

**Issue by pratikmts** [MyThemeShopTeam/WP-Review#94]
**Describe the bug**
When we select Snippet type from Rank options, it resets to none after publishing the post.

**To Reproduce**
1. Select Rich Snippet type from RM metabox
2. Publish post
3. Scroll down to Rich Snippet option in RM metabox

**Screenshots**
Frontend: http://take.ms/fq3lb
Backend: http://take.ms/1B4sC

**Comment by truong-mts** [comment]
@pratikmts I'm not sure why we have this code in this plugin https://github.com/MyThemeShopTeam/WP-Review/blob/master/admin/assets/js/admin.js#L194
