### ISSUE TITLE
New issues after recent changes related to PHPCS

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/WP-Review#97]
- [x] http://take.ms/WVAIL by default this is how it is showing, box order is changed
- [x] These two boxes (Review Links, User Reviews) should be hidden until the review type is selected.
- [x] Bars are gone from the backend http://take.ms/pHMC9
- [x] Count is not increasing after user rates http://take.ms/YBGH1 (Need a page reload to see the new count)
- [x] If we edit any rating from the **comments** area, there is a filed called **Review Title**, are we using it anywhere in the free version? http://take.ms/8g9K3

**Comment by truong-mts** [comment]
I can't replicate 1 on my local. 4 and 5 also occur in WP Review Pro so they are not related to recent commits.

For 1, please make sure that you didn't sort those meta boxes
For 5, we are not use Review Title for visitors  rating.
